# _config.yml

title: Mohammad Reza Nilchiyan
description: Welcome to my personal webpage!
theme: jekyll-theme-minimal

# Navigation links
nav_links:
  - text: Home
    url: /
  - text: About Me
    url: /about

# Social links
social_icons:
  - icon: fab fa-github
    url: https://github.com/yourusername
  # Add more social icons as needed

# Build settings
markdown: kramdown

# Jekyll SEO Tag settings
plugins:
  - jekyll-seo-tag

# Permalinks for posts and pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      permalink: /:title/

# More Jekyll and site-related settings can be added here
