# _config.yml

title: "Mohammad Reza Nilchiyan"
author: "Mohammad Reza"
description: "Universiti Teknologi Malaysia (UTM)"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_excerpts: false
show_frame: true
show_sidebar: false
minimal: false

# Menu
navigation:
  - {file: "index.html", title: "Home", icon: "home"}
  - {file: "about.html", title: "About Me", icon: "address-card"}
  - {file: "publications.html", title: "Publications", icon: "book"}
  - {file: "honors.html", title: "Honors", icon: "trophy"}
  - {file: "certificates.html", title: "Certificates", icon: "certificate"}

external:
  - {title: "Mail", icon: "envelope", url: "mailto:m.r.nilchiyan@fkegraduate.utm.my"}
  - {title: "Github", icon: "github", url: "https://github.com/mohammadRezanilchiyan"}
  - {title: "LinkedIn", icon: "linkedin", url: "https://www.linkedin.com/in/drmohammadrezanilchiyan/"}

# Plugins
plugins:
  - jekyll-feed

# Add any other Jekyll and site-related settings as needed
